### ISSUE TITLE
Experience a bit jerky on Android

### ISSUE THREAD

**Issue by prashanthselvam** [macvish/react-native-basic-carousel#2]
Hey there! I've been using this carousel component for an app and it's worked really well on iOS. I'm getting my Android release ready and am noticing the behavior feels much less snappy on Android. Basically as you swipe through the carousel, the items don't quite move the way you'd expect them to and it kind of stops and starts a lot. I looked into the source code but couldn't immediately tell why this might be happening. Any tips/suggestions on how this could be addressed? Thanks!

**Comment by macvish** [comment]
Hi @prashanthselvam, thank you for using this RN package, can you kindly send a sample video recording of this issue?

**Comment by prashanthselvam** [comment]
Hey @macvish - sorry for the delay in getting back to you. I've attached below 2 videos of the same experience on iOS vs android. Not totally sure if it comes across in the video but on Android basically once you complete the swipe, the card seems to slow down - in other words it doesn't seem to maintain the momentum of the swipe which feels somewhat strange as the user. If you have any tips or fixes that would be very helpful! And thanks so much for creating this package.

https://github.com/macvish/react-native-basic-carousel/assets/7219287/602b752a-48e0-4c05-9436-50e140996b86

https://github.com/macvish/react-native-basic-carousel/assets/7219287/121afc71-b5ca-4667-8e4b-ac16a84dd1e7

**Comment by macvish** [comment]
So, I've tried a couple fixes and still the same outcome, it's safe to say this is probably native to android when using the swipe gesture, but the momentum is as fast iOS when on autoplay or if you change the index manually. If you found any possible solutions to this, please do let me know... Thanks for using the package.
