### ISSUE TITLE
jump to index

### ISSUE THREAD

**Issue by Ali72** [macvish/react-native-basic-carousel#4]
How can I jump to a specific index? I want to keep a reference to the carousel, and when a button is pressed, it should jump to a specific index of the carousel with/without animation.

ex: open page and it starts carousel from specific index (not zero)

**Comment by macvish** [comment]
You could use the `scrollToIndex` method, `ref.current.scrollToIndex({ index: 1 }),`. but I could also add `snapToNext` and `snapToPrev` method too
